### ISSUE TITLE
Aizea

### ISSUE THREAD

**Issue by aizeapaulin** [DeustoPWEB/pweb2017#2]

**Comment by mirenbz** [comment]
Kaixo @aizeapaulin , ez da beharrezkoa issue bat zabaltzea hemen arazorik ez baduzu. Bai da beharrezkoa, ordea, [pull request berri bat egitea](https://github.com/DeustoPWEB/pweb2017/pulls), zure kodea (izena eta link-a) repositorio nagusira gehitu dezadan. 

Issue hau itxi egingo dut, eta pull request-a egiten duzunean, arazorik sortuko balitz hor jarraituko dugu elkarrizketa. Animo!
