### ISSUE TITLE
Ander 

### ISSUE THREAD

**Issue by anderbarri** [DeustoPWEB/pweb2017#3]

**Comment by mirenbz** [comment]
Kaixo @anderbarri , no hace falta que abras un issue aquí si no has tenido ningún problema. He visto que has hecho el pull request #4 pero tiene un error, te he dejado un mensaje allí que supongo que también habrás recibido por email. Cuando lo resuelvas vuelve a hacer un nuevo pull request. 

Voy a cerrar este issue, y cuando tengas el nuevo pull request, podemos seguir la conversación allí en caso de que haya algún problema. Ánimo!
