### ISSUE TITLE
María Jaén

### ISSUE THREAD

**Issue by mjaenh** [DeustoPWEB/pweb2017#5]

**Comment by mirenbz** [comment]
Hola @mjaenh , no hace falta que abras un issue aquí si no has tenido ningún problema. Sí hace falta, sin embargo, que [abras un nuevo pull request](https://github.com/DeustoPWEB/pweb2017/pulls) para que pueda integrar tu código (tu nombre y enlace en el listado de estudiantes) en el branch principal `master`. 

Voy a cerrar este issue, y cuando tengas el nuevo pull request, podemos seguir la conversación allí en caso de que haya algún problema. Ánimo!
